// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260118005227_SeedGymClasses-2")]
    partial class SeedGymClasses2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.GymClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCapacityUser")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GymClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Clase de relajación y estiramiento",
                            Dia = 1,
                            DuracionMinutos = 60,
                            Hora = "08:00",
                            ImageUrl = "https://placehold.co/600x400?text=Yoga&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "Yoga"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Clase de relajación y estiramiento",
                            Dia = 1,
                            DuracionMinutos = 60,
                            Hora = "18:00",
                            ImageUrl = "https://placehold.co/600x400?text=Yoga&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "Yoga"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Clase de relajación y estiramiento",
                            Dia = 3,
                            DuracionMinutos = 60,
                            Hora = "08:00",
                            ImageUrl = "https://placehold.co/600x400?text=Yoga&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "Yoga"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Clase de relajación y estiramiento",
                            Dia = 3,
                            DuracionMinutos = 60,
                            Hora = "19:00",
                            ImageUrl = "https://placehold.co/600x400?text=Yoga&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "Yoga"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Clase de relajación y estiramiento",
                            Dia = 5,
                            DuracionMinutos = 60,
                            Hora = "08:00",
                            ImageUrl = "https://placehold.co/600x400?text=Yoga&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "Yoga"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Clase de relajación y estiramiento",
                            Dia = 5,
                            DuracionMinutos = 60,
                            Hora = "17:00",
                            ImageUrl = "https://placehold.co/600x400?text=Yoga&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "Yoga"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Entrenamiento funcional de alta intensidad",
                            Dia = 2,
                            DuracionMinutos = 45,
                            Hora = "07:00",
                            ImageUrl = "https://placehold.co/600x400?text=CrossFit&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "CrossFit"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Entrenamiento funcional de alta intensidad",
                            Dia = 2,
                            DuracionMinutos = 45,
                            Hora = "19:00",
                            ImageUrl = "https://placehold.co/600x400?text=CrossFit&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "CrossFit"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Entrenamiento funcional de alta intensidad",
                            Dia = 4,
                            DuracionMinutos = 45,
                            Hora = "07:00",
                            ImageUrl = "https://placehold.co/600x400?text=CrossFit&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "CrossFit"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Entrenamiento funcional de alta intensidad",
                            Dia = 4,
                            DuracionMinutos = 45,
                            Hora = "20:00",
                            ImageUrl = "https://placehold.co/600x400?text=CrossFit&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "CrossFit"
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "Entrenamiento funcional de alta intensidad",
                            Dia = 6,
                            DuracionMinutos = 45,
                            Hora = "09:00",
                            ImageUrl = "https://placehold.co/600x400?text=CrossFit&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "CrossFit"
                        },
                        new
                        {
                            Id = 12,
                            Descripcion = "Entrenamiento funcional de alta intensidad",
                            Dia = 6,
                            DuracionMinutos = 45,
                            Hora = "11:00",
                            ImageUrl = "https://placehold.co/600x400?text=CrossFit&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "CrossFit"
                        },
                        new
                        {
                            Id = 13,
                            Descripcion = "Ejercicio cardiovascular en bicicleta",
                            Dia = 1,
                            DuracionMinutos = 50,
                            Hora = "20:00",
                            ImageUrl = "https://placehold.co/600x400?text=Spinning&font=montserrat",
                            MaxCapacityUser = 15,
                            Nombre = "Spinning"
                        },
                        new
                        {
                            Id = 14,
                            Descripcion = "Ejercicio cardiovascular en bicicleta",
                            Dia = 2,
                            DuracionMinutos = 50,
                            Hora = "20:00",
                            ImageUrl = "https://placehold.co/600x400?text=Spinning&font=montserrat",
                            MaxCapacityUser = 15,
                            Nombre = "Spinning"
                        },
                        new
                        {
                            Id = 15,
                            Descripcion = "Ejercicio cardiovascular en bicicleta",
                            Dia = 3,
                            DuracionMinutos = 50,
                            Hora = "20:00",
                            ImageUrl = "https://placehold.co/600x400?text=Spinning&font=montserrat",
                            MaxCapacityUser = 15,
                            Nombre = "Spinning"
                        },
                        new
                        {
                            Id = 16,
                            Descripcion = "Ejercicio cardiovascular en bicicleta",
                            Dia = 4,
                            DuracionMinutos = 50,
                            Hora = "20:00",
                            ImageUrl = "https://placehold.co/600x400?text=Spinning&font=montserrat",
                            MaxCapacityUser = 15,
                            Nombre = "Spinning"
                        },
                        new
                        {
                            Id = 17,
                            Descripcion = "Ejercicio cardiovascular en bicicleta",
                            Dia = 5,
                            DuracionMinutos = 50,
                            Hora = "20:00",
                            ImageUrl = "https://placehold.co/600x400?text=Spinning&font=montserrat",
                            MaxCapacityUser = 15,
                            Nombre = "Spinning"
                        },
                        new
                        {
                            Id = 18,
                            Descripcion = "Ejercicio cardiovascular en bicicleta",
                            Dia = 6,
                            DuracionMinutos = 50,
                            Hora = "18:00",
                            ImageUrl = "https://placehold.co/600x400?text=Spinning&font=montserrat",
                            MaxCapacityUser = 15,
                            Nombre = "Spinning"
                        },
                        new
                        {
                            Id = 19,
                            Descripcion = "Fortalecimiento y control postural",
                            Dia = 2,
                            DuracionMinutos = 55,
                            Hora = "18:00",
                            ImageUrl = "https://placehold.co/600x400?text=Pilates&font=montserrat",
                            MaxCapacityUser = 5,
                            Nombre = "Pilates"
                        },
                        new
                        {
                            Id = 20,
                            Descripcion = "Fortalecimiento y control postural",
                            Dia = 4,
                            DuracionMinutos = 55,
                            Hora = "18:00",
                            ImageUrl = "https://placehold.co/600x400?text=Pilates&font=montserrat",
                            MaxCapacityUser = 5,
                            Nombre = "Pilates"
                        },
                        new
                        {
                            Id = 21,
                            Descripcion = "Fortalecimiento y control postural",
                            Dia = 6,
                            DuracionMinutos = 55,
                            Hora = "10:00",
                            ImageUrl = "https://placehold.co/600x400?text=Pilates&font=montserrat",
                            MaxCapacityUser = 5,
                            Nombre = "Pilates"
                        },
                        new
                        {
                            Id = 22,
                            Descripcion = "Técnica, sacos y condición física",
                            Dia = 1,
                            DuracionMinutos = 60,
                            Hora = "19:00",
                            ImageUrl = "https://placehold.co/600x400?text=Boxeo&font=montserrat",
                            MaxCapacityUser = 8,
                            Nombre = "Boxeo"
                        },
                        new
                        {
                            Id = 23,
                            Descripcion = "Técnica, sacos y condición física",
                            Dia = 3,
                            DuracionMinutos = 60,
                            Hora = "19:00",
                            ImageUrl = "https://placehold.co/600x400?text=Boxeo&font=montserrat",
                            MaxCapacityUser = 8,
                            Nombre = "Boxeo"
                        },
                        new
                        {
                            Id = 24,
                            Descripcion = "Técnica, sacos y condición física",
                            Dia = 5,
                            DuracionMinutos = 60,
                            Hora = "19:00",
                            ImageUrl = "https://placehold.co/600x400?text=Boxeo&font=montserrat",
                            MaxCapacityUser = 8,
                            Nombre = "Boxeo"
                        },
                        new
                        {
                            Id = 25,
                            Descripcion = "Baile y ritmo latino para quemar calorías",
                            Dia = 2,
                            DuracionMinutos = 50,
                            Hora = "20:30",
                            ImageUrl = "https://placehold.co/600x400?text=Zumba&font=montserrat",
                            MaxCapacityUser = 20,
                            Nombre = "Zumba"
                        },
                        new
                        {
                            Id = 26,
                            Descripcion = "Baile y ritmo latino para quemar calorías",
                            Dia = 4,
                            DuracionMinutos = 50,
                            Hora = "20:30",
                            ImageUrl = "https://placehold.co/600x400?text=Zumba&font=montserrat",
                            MaxCapacityUser = 20,
                            Nombre = "Zumba"
                        },
                        new
                        {
                            Id = 27,
                            Descripcion = "Baile y ritmo latino para quemar calorías",
                            Dia = 6,
                            DuracionMinutos = 50,
                            Hora = "12:00",
                            ImageUrl = "https://placehold.co/600x400?text=Zumba&font=montserrat",
                            MaxCapacityUser = 20,
                            Nombre = "Zumba"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InitPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<string>("PreferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fecha = "2025-10-10",
                            Monto = 25.0m,
                            Pagado = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Fecha = "2025-11-10",
                            Monto = 25.0m,
                            Pagado = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Fecha = "2025-10-10",
                            Monto = 45.0m,
                            Pagado = true,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Precio = 25.0m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Precio = 45.0m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            Precio = 70.0m,
                            Tipo = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Socio"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "SuperAdministrador"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "uno",
                            Contraseña = "AQAAAAIAAYagAAAAEGcgHZBzkJyzCmzJJ5Pdsgag79UZFtiD+D1XULIXJofHI/dZ0NBxS5PBVIk3tSwCeg==",
                            Email = "cliente@demo.com",
                            Nombre = "cliente",
                            PlanId = 1,
                            RoleId = 1,
                            Telefono = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "demo",
                            Contraseña = "AQAAAAIAAYagAAAAEHr55677YyvbxlxG8FCwdiQXHQA/pqkYGZWiQ0EZQtvGRoO929SMzEL7pb9vRFHdoQ==",
                            Email = "admin@demo.com",
                            Nombre = "admin",
                            RoleId = 2,
                            Telefono = "5678"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "demo",
                            Contraseña = "AQAAAAIAAYagAAAAEPbUTnhM37g74/SS0FJ84lkyPR/NQUV9kxbzR9Ij4xpu+Id9iLHhHVydLvP1h2l1bw==",
                            Email = "superadmin@demo.com",
                            Nombre = "superadmin",
                            RoleId = 3,
                            Telefono = "9999"
                        });
                });

            modelBuilder.Entity("GymClassUser", b =>
                {
                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<int>("GymClassesId")
                        .HasColumnType("int");

                    b.HasKey("UsersId", "GymClassesId");

                    b.HasIndex("GymClassesId");

                    b.ToTable("UserGymClass", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Pagos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Plan", "Plan")
                        .WithMany("Users")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Role", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GymClassUser", b =>
                {
                    b.HasOne("Domain.Entities.GymClass", null)
                        .WithMany()
                        .HasForeignKey("GymClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Plan", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
