// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260211203558_RemovePlanFromUserAddingSubscription")]
    partial class RemovePlanFromUserAddingSubscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.GymClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCapacityUser")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GymClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Clase de relajación y estiramiento",
                            Dia = 1,
                            DuracionMinutos = 60,
                            Hora = "08:00",
                            ImageUrl = "https://placehold.co/600x400?text=Yoga&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "Yoga"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Clase de relajación y estiramiento",
                            Dia = 3,
                            DuracionMinutos = 60,
                            Hora = "08:00",
                            ImageUrl = "https://placehold.co/600x400?text=Yoga&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "Yoga"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Clase de relajación y estiramiento",
                            Dia = 5,
                            DuracionMinutos = 60,
                            Hora = "08:00",
                            ImageUrl = "https://placehold.co/600x400?text=Yoga&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "Yoga"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Entrenamiento funcional de alta intensidad",
                            Dia = 2,
                            DuracionMinutos = 45,
                            Hora = "07:00",
                            ImageUrl = "https://placehold.co/600x400?text=CrossFit&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "CrossFit"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Entrenamiento funcional de alta intensidad",
                            Dia = 4,
                            DuracionMinutos = 45,
                            Hora = "20:00",
                            ImageUrl = "https://placehold.co/600x400?text=CrossFit&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "CrossFit"
                        },
                        new
                        {
                            Id = 12,
                            Descripcion = "Entrenamiento funcional de alta intensidad",
                            Dia = 6,
                            DuracionMinutos = 45,
                            Hora = "11:00",
                            ImageUrl = "https://placehold.co/600x400?text=CrossFit&font=montserrat",
                            MaxCapacityUser = 3,
                            Nombre = "CrossFit"
                        },
                        new
                        {
                            Id = 13,
                            Descripcion = "Ejercicio cardiovascular en bicicleta",
                            Dia = 1,
                            DuracionMinutos = 50,
                            Hora = "20:00",
                            ImageUrl = "https://placehold.co/600x400?text=Spinning&font=montserrat",
                            MaxCapacityUser = 15,
                            Nombre = "Spinning"
                        },
                        new
                        {
                            Id = 14,
                            Descripcion = "Ejercicio cardiovascular en bicicleta",
                            Dia = 2,
                            DuracionMinutos = 50,
                            Hora = "20:00",
                            ImageUrl = "https://placehold.co/600x400?text=Spinning&font=montserrat",
                            MaxCapacityUser = 15,
                            Nombre = "Spinning"
                        },
                        new
                        {
                            Id = 15,
                            Descripcion = "Ejercicio cardiovascular en bicicleta",
                            Dia = 3,
                            DuracionMinutos = 50,
                            Hora = "20:00",
                            ImageUrl = "https://placehold.co/600x400?text=Spinning&font=montserrat",
                            MaxCapacityUser = 15,
                            Nombre = "Spinning"
                        },
                        new
                        {
                            Id = 19,
                            Descripcion = "Fortalecimiento y control postural",
                            Dia = 2,
                            DuracionMinutos = 55,
                            Hora = "18:00",
                            ImageUrl = "https://placehold.co/600x400?text=Pilates&font=montserrat",
                            MaxCapacityUser = 5,
                            Nombre = "Pilates"
                        },
                        new
                        {
                            Id = 20,
                            Descripcion = "Fortalecimiento y control postural",
                            Dia = 4,
                            DuracionMinutos = 55,
                            Hora = "18:00",
                            ImageUrl = "https://placehold.co/600x400?text=Pilates&font=montserrat",
                            MaxCapacityUser = 5,
                            Nombre = "Pilates"
                        },
                        new
                        {
                            Id = 21,
                            Descripcion = "Fortalecimiento y control postural",
                            Dia = 6,
                            DuracionMinutos = 55,
                            Hora = "10:00",
                            ImageUrl = "https://placehold.co/600x400?text=Pilates&font=montserrat",
                            MaxCapacityUser = 5,
                            Nombre = "Pilates"
                        },
                        new
                        {
                            Id = 22,
                            Descripcion = "Técnica, sacos y condición física",
                            Dia = 1,
                            DuracionMinutos = 60,
                            Hora = "19:00",
                            ImageUrl = "https://placehold.co/600x400?text=Boxeo&font=montserrat",
                            MaxCapacityUser = 8,
                            Nombre = "Boxeo"
                        },
                        new
                        {
                            Id = 23,
                            Descripcion = "Técnica, sacos y condición física",
                            Dia = 3,
                            DuracionMinutos = 60,
                            Hora = "19:00",
                            ImageUrl = "https://placehold.co/600x400?text=Boxeo&font=montserrat",
                            MaxCapacityUser = 8,
                            Nombre = "Boxeo"
                        },
                        new
                        {
                            Id = 24,
                            Descripcion = "Técnica, sacos y condición física",
                            Dia = 5,
                            DuracionMinutos = 60,
                            Hora = "19:00",
                            ImageUrl = "https://placehold.co/600x400?text=Boxeo&font=montserrat",
                            MaxCapacityUser = 8,
                            Nombre = "Boxeo"
                        },
                        new
                        {
                            Id = 25,
                            Descripcion = "Baile y ritmo latino para quemar calorías",
                            Dia = 2,
                            DuracionMinutos = 50,
                            Hora = "20:30",
                            ImageUrl = "https://placehold.co/600x400?text=Zumba&font=montserrat",
                            MaxCapacityUser = 20,
                            Nombre = "Zumba"
                        },
                        new
                        {
                            Id = 26,
                            Descripcion = "Baile y ritmo latino para quemar calorías",
                            Dia = 4,
                            DuracionMinutos = 50,
                            Hora = "20:30",
                            ImageUrl = "https://placehold.co/600x400?text=Zumba&font=montserrat",
                            MaxCapacityUser = 20,
                            Nombre = "Zumba"
                        },
                        new
                        {
                            Id = 27,
                            Descripcion = "Baile y ritmo latino para quemar calorías",
                            Dia = 6,
                            DuracionMinutos = 50,
                            Hora = "12:00",
                            ImageUrl = "https://placehold.co/600x400?text=Zumba&font=montserrat",
                            MaxCapacityUser = 20,
                            Nombre = "Zumba"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("InitPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<string>("PreferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fecha = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 25.0m,
                            Pagado = false,
                            SubscriptionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Fecha = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 25.0m,
                            Pagado = true,
                            SubscriptionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Fecha = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 45.0m,
                            Pagado = true,
                            SubscriptionId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Precio = 25.0m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Precio = 45.0m,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            Precio = 70.0m,
                            Tipo = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Socio"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "SuperAdministrador"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PlanId = 1,
                            StartDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PlanId = 2,
                            StartDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "uno",
                            Contraseña = "AQAAAAIAAYagAAAAECV99eopkaXJB7mylI9M5lOVR3X0ugfP/ogduxPJJMFkQUJE8pYczgQmF4ER4oGTHA==",
                            Email = "cliente@demo.com",
                            Nombre = "cliente",
                            RoleId = 1,
                            Telefono = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "demo",
                            Contraseña = "AQAAAAIAAYagAAAAEFMPITMIAhLP3INx8RKIDR9ptVPTFqYCt3P+A2mb3MiWi0RoWovzjrZjDWzoUVXycA==",
                            Email = "admin@demo.com",
                            Nombre = "admin",
                            RoleId = 2,
                            Telefono = "5678"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "demo",
                            Contraseña = "AQAAAAIAAYagAAAAELt2q2gb7/fHYD3WRrS8/XsvRPu07Vc0Snme+lnpJqw8DWlFBIGPDerx/0uNldPT9w==",
                            Email = "superadmin@demo.com",
                            Nombre = "superadmin",
                            RoleId = 3,
                            Telefono = "9999"
                        });
                });

            modelBuilder.Entity("GymClassUser", b =>
                {
                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.Property<int>("GymClassesId")
                        .HasColumnType("int");

                    b.HasKey("UsersId", "GymClassesId");

                    b.HasIndex("GymClassesId");

                    b.ToTable("UserGymClass", (string)null);
                });

            modelBuilder.Entity("Historical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ClassDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GymClassId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymClassId");

                    b.HasIndex("UserId");

                    b.ToTable("Historicals");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Pagos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GymClassUser", b =>
                {
                    b.HasOne("Domain.Entities.GymClass", null)
                        .WithMany()
                        .HasForeignKey("GymClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Historical", b =>
                {
                    b.HasOne("Domain.Entities.GymClass", "GymClass")
                        .WithMany("Historicals")
                        .HasForeignKey("GymClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Historicals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymClass");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.GymClass", b =>
                {
                    b.Navigation("Historicals");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Historicals");

                    b.Navigation("Pagos");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
